url: "https://sloanelybutsurely.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "sloanelybutsurely.com" # the name of your site, e.g. ACME Corp.
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-compose
  - jekyll-webmention_io

webmentions:
  username: sloanelybutsurely.com
  cache_folder: _data
  legacy_domains:
    - http://sloane.sh
    - https://sloane.sh
    - http://sloanelybutsurely.com
  bad_uri_policy:
    whitelist:
       - "^https://brid.gy/publish/"
  syndication:
    mastodon:
      endpoint: https://brid.gy/publish/mastodon
      response_mapping:
        syndication: $.url
    bluesky:
      endpoint: https://brid.gy/publish/bluesky
      response_mapping:
        syndication: $.url

author:
  name: sloane
  url: "https://sloanelybutsurely.com"
