url: "https://sloane.sh" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "sloane.sh" # the name of your site, e.g. ACME Corp.
permalink: /:categories/:year/:month/:day/:title/index:output_ext
plugins:
  - jekyll-compose
  - jekyll-webmention_io

webmentions:
  username: sloane.sh
  syndication:
    mastodon:
      endpoint: https://brid.gy/publish/mastodon
    bluesky:
      endpoint: https://brid.gy/publish/bluesky

author:
  name: sloane
  url: "https://sloane.sh"
